### PR TITLE
Update pants to 1.3.0

### PR DESCRIPTION
**Pull request by OlafurD**

### CODE REVIEW

**Comment by thesamet** [comment]
Thank you - since this project is lacking unit tests :( - were you able to verify that this change works?

**Comment by OlafurD** [comment]
Yes, verified on my own code base 👍

**Comment by joshlreese** [comment]
Thanks for merging this @thesamet (and for the patch @OlafurD). I've confirmed this works with 1.4.0dev21 as well. Could we possibly get an updated version in PyPI?

**Comment by thesamet** [comment]
@joshlreese @OlafurD I released v0.1.6 of this plugin to pypi. The example at https://github.com/scalapb/scalapb-pants-example has been updated as well.

**Pull request merged**
